# Generated by Django 5.2 on 2025-06-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100, unique=True, verbose_name='Exame')),
                ('description', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Descrição')),
                ('preparation', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Preparação')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['exam_name'],
            },
        ),
    ]
