# Generated by Django 5.2 on 2025-06-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpositionRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Exposição')),
                ('description', models.TextField(max_length=1200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Exposição',
                'verbose_name_plural': 'Tipos de Exposição',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Risco')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Risco de Acidente',
                'verbose_name_plural': 'Riscos de Acidentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskBiological',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Risco')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Risco Biológico',
                'verbose_name_plural': 'Riscos Biológicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Risco')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Risco Químico',
                'verbose_name_plural': 'Riscos Químicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskErgonomic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Risco')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Risco Ergonômico',
                'verbose_name_plural': 'Riscos Ergonômicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskPhysical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Risco')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Risco Físico',
                'verbose_name_plural': 'Riscos Físicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeEpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo de EPI')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de EPI',
                'verbose_name_plural': 'Tipos de EPI',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='EPI')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('type_epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='safety.typeepi', verbose_name='Tipo de EPI')),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'ordering': ['name'],
            },
        ),
    ]
