# Generated by Django 5.2 on 2025-06-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_alter_expositionrisk_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskchemical',
            name='type_risk_chemical',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Tipo de Risco Químico'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='riskaccident',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='riskbiological',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='riskchemical',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='riskergonomic',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='riskphysical',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='typeepi',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Descrição'),
        ),
    ]
