# Generated by Django 5.2 on 2025-06-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='description',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Descrição da Função'),
        ),
        migrations.AlterField(
            model_name='specialactivity',
            name='description',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Descrição'),
        ),
    ]
